name: Update XML on Release

on:
  release:
    types:
      - published

jobs:
  update-xml:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Create ZIP Archive
        run: |
          git clone https://giactitti:$API_TOKEN_GITHUB@github.com/geo2mod/QGINLA.git to_zip
          cd to_zip
          zip -r qginla.zip ./qginla
          cd ..
          
          TAG_NAME=${{ github.event.release.tag_name }}
          # Clone the repository where the XML file is stored
          git clone https://giactitti:$API_TOKEN_GITHUB@github.com/geo2mod/geo2mod.github.io.git xml-repo

          # Modify the XML file with the desired version
          sed -i 's/name="QGINLA" version=\"[^\"]*\"/name="QGINLA" version="'"$TAG_NAME"'"/' xml-repo/qginla/qginla.xml
          cp -f ./to_zip/qginla.zip ./xml-repo/qginla/
          
          # Commit and push the changes
          cd xml-repo
          git config user.name "giactitti"
          git config user.email "giacomotitti@gmail.com"
          git commit -am "Update XML version"
          git remote set-url origin https://giactitti:$API_TOKEN_GITHUB@github.com/geo2mod/geo2mod.github.io.git
          git push origin
        env:
          API_TOKEN_GITHUB: ${{ secrets.GIT_PAT_TOKEN }}
